version: "3.9"

services:
  mongodb:
    container_name: app-mongodb
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      backend:

volumes:
  dbdata:

networks:
  backend:
    driver: bridge